namespace LedgerPro.Core.Enums;

public enum GeneralLedgerAccountType
{
    Asset,      // Represents resources owned by the company (e.g., Cash, Accounts Receivable, Inventory)
    Liability,  // Represents obligations owed to others (e.g., Accounts Payable, Loans)
    Equity,     // Represents the owner's interest in the company (e.g., Common Stock, Retained Earnings)
    Revenue,    // Represents income generated by the company's operations
    Expense     // Represents costs incurred by the company in generating revenue
}
