// <auto-generated />
using System;
using LedgerPro.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LedgerPro.Infrastructure.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LedgerPro.Core.Entities.BankSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankSources");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<Guid>("BankSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatementImportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankSourceId");

                    b.HasIndex("StatementImportId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.BankTransactionMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetGeneralLedgerAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetGeneralLedgerAccountId");

                    b.ToTable("BankTransactionMappings");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.FinancialPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinancialPeriods");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.GeneralLedgerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralLedgerAccounts");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.GeneralLedgerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("BankTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneralLedgerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("GeneralLedgerAccountId");

                    b.ToTable("GeneralLedgerItems");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.StatementImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankSourceId");

                    b.ToTable("StatementImports");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.BankTransaction", b =>
                {
                    b.HasOne("LedgerPro.Core.Entities.BankSource", "BankSource")
                        .WithMany("BankTransactions")
                        .HasForeignKey("BankSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LedgerPro.Core.Entities.StatementImport", "StatementImport")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankSource");

                    b.Navigation("StatementImport");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.BankTransactionMapping", b =>
                {
                    b.HasOne("LedgerPro.Core.Entities.GeneralLedgerAccount", "TargetGeneralLedgerAccount")
                        .WithMany()
                        .HasForeignKey("TargetGeneralLedgerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGeneralLedgerAccount");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.GeneralLedgerItem", b =>
                {
                    b.HasOne("LedgerPro.Core.Entities.BankTransaction", "BankTransaction")
                        .WithMany()
                        .HasForeignKey("BankTransactionId");

                    b.HasOne("LedgerPro.Core.Entities.GeneralLedgerAccount", "GeneralLedgerAccount")
                        .WithMany()
                        .HasForeignKey("GeneralLedgerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankTransaction");

                    b.Navigation("GeneralLedgerAccount");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.StatementImport", b =>
                {
                    b.HasOne("LedgerPro.Core.Entities.BankSource", "BankSource")
                        .WithMany("StatementImports")
                        .HasForeignKey("BankSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankSource");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.BankSource", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("StatementImports");
                });

            modelBuilder.Entity("LedgerPro.Core.Entities.StatementImport", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
